# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Repository root
  command = "npm run build"
  publish = "packages/frontend/dist/"
  functions = "packages/backend/netlify/functions/" # Updated functions directory
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_OMIT_PATHS = [
    "README.md",
    "all_markdown_and_code_snapshot_llm_distilled.txt",
    "packages/frontend/dist/assets/*.js"
  ]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Removed [secrets] section and all secrets scanning related settings
