# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Explicitly set base to the root of the repository
  command = "node scripts/preprocess-md.js && npm run build" # Updated command
  publish = "vite-app/dist/"
  functions = "netlify/functions/"
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  # Omit paths from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = [
    "vite-app/dist/**/*.js",
    "TASKS.md",
    "agents/*.md",
    "all_markdown_and_code_snapshot_llm_distilled.txt",
    "vite-app/SUPABASE_DATABASE_AND_AUTH_SETUP.md"
  ]
  SECRETS_SCAN_ENABLED = false # Disable secrets scanning

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[secrets]
  omit_keys = [
    "VITE_SUPABASE_URL",
    "VITE_SUPABASE_ANON_KEY",
    "FRONTEND_BASE_URL",
    "BACKEND_BASE_URL",
    "PLAYWRIGHT_MCP_SERVER_URL"
  ]
