# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Repository root
  command = "npm run build"
  publish = "packages/frontend/dist/"
  functions = "packages/backend/netlify/functions/" # Updated functions directory
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_OMIT_PATHS = [
    "README.md",
    "all_markdown_and_code_snapshot_llm_distilled.txt",
    "packages/frontend/dist/assets/*.js"
  ]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# ===================================================================
# THE DEFINITIVE FIX: Function Bundler Configuration
# ===================================================================
# This tells Netlify's bundler how to handle our backend function.
[functions]
  # Apply these rules to our main API function.
  "api-mjs" = {
    # Tell the bundler to NOT bundle these specific packages.
    # Instead, Netlify will include them in the function's node_modules
    # so they can be required/imported at runtime, just like in local dev.
    external_node_modules = [
      "express",
      "cors",
      "serverless-http",
      "dotenv",
      "supabase",
      "@supabase/supabase-js"
    ]
  }

# Removed [secrets] section and all secrets scanning related settings
