# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Repository root
  command = "npm install --include=dev && npx vitest run && npm --workspace=@plumbingpoc/frontend run build"
  publish = "packages/frontend/dist/"
  functions = "packages/backend/netlify/functions/" # Updated functions directory
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_OMIT_PATHS = [
    "README.md",
    "all_markdown_and_code_snapshot_llm_distilled.txt",
    "packages/frontend/dist/assets/*.js"
  ]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# ===================================================================
# THE DEFINITIVE FIX: Function Bundler Configuration
# ===================================================================
# This tells Netlify's bundler how to handle our backend functions.
# Note the correct TOML syntax: [functions."function-name"]
[functions]

  # Configuration for the main API function
  [functions.api]
    # Tell the bundler to NOT bundle these specific packages.
    # Instead, Netlify will include them in the function's node_modules
    # so they can be required/imported at runtime, just like in local dev.
    external_node_modules = [
      "express",
      "cors",
      "serverless-http",
      "dotenv",
      "supabase",
      "@supabase/supabase-js",
      "yaml",
      "openai"
    ]
    # Include the YAML config file since quoteAgentRunner is imported by requestRoutes
    included_files = [
      "agents/quote-agent.yaml",
      "agents/triage-agent.yaml"
    ]

  # Configuration for the SMS function
  [functions.send-sms]
    external_node_modules = ["twilio"]

  # Configuration for the quote agent function
  [functions."quote-agent"]
    external_node_modules = [
      "yaml",
      "openai"
    ]
    included_files = [
      "agents/quote-agent.yaml"
    ]

  # Configuration for the triage agent function
  [functions."triage-agent"]
    external_node_modules = [
      "yaml",
      "openai"
    ]
    included_files = [
      "agents/triage-agent.yaml"
    ]

# Removed [secrets] section and all secrets scanning related settings
