# netlify.toml (v2 - Corrected Paths)

[build]
  # The base directory where the build command is run
  base    = "vite-app/"
  # The build command for the Vite frontend
  command = "npm run build"
  # The directory where the built frontend files are located,
  # relative to the `base` directory.
  publish = "dist/"
  # The directory for serverless functions,
  # relative to the `base` directory.
  functions = "netlify/functions/"

# Redirect API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[secrets]
  # Add the keys of environment variables that are safe to be exposed.
  # These are typically keys prefixed with VITE_ for frontend use.
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]