# netlify.toml (v3 - Root Configuration)

[build]
  # Build command now includes the path to the vite app
  command = "npm run build"
  # Publish directory is now a direct path from the root
  publish = "vite-app/dist/"
  # Functions directory is also a direct path from the root
  functions = "netlify/functions/" # <-- We need to move the netlify folder

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[secrets]
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]
