# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Explicitly set base to the root of the repository
  command = "node scripts/preprocess-md.js && npm run build" # Updated command
  publish = "vite-app/dist/"
  functions = "netlify/functions/"
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  # Omit paths from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = [
    "vite-app/dist/**/*.js"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[secrets]
  omit_keys = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]