# netlify.toml (v3 - Root Configuration)

[build]
  base = "." # Explicitly set base to the root of the repository
  command = "npm run build" # Reverted command
  publish = "vite-app/dist/"
  functions = "netlify/functions/"
  environment = { NPM_FLAGS = "--legacy-peer-deps" }
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_OMIT_PATHS = [
    "README.md",
    "all_markdown_and_code_snapshot_llm_distilled.txt",
    "vite-app/dist/assets/*.js"
  ]
  SECRETS_SCAN_OMIT_KEYS = [
    "VITE_BACKEND_BASE_URL",
    "VITE_SUPABASE_ANON_KEY",
    "VITE_SUPABASE_URL"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Removed [secrets] section and all secrets scanning related settings
